minio:
  endpoint: "localhost:9000"
  # access-key-id: "xnZSeBX60hUtxqEaNwRe"
  # secret-access-key: "KCT2Vk1LeAJgYC1Wuwxows06T6gYnbF31K6CW5Qd"
  access-key-id: "your-access-key-id"
  secret-access-key: "your-secret-access-key"
  encryption-key-id: "your-encryption-key-id"
  bucket: "testbucket"
  region: "us-east-1"
  enable-multipart-upload: true
  file-chunk-size: 5 # Minimum 5MiB

# Server configurations
server:
  api-path: "api"
  api-version: "v1"
  cors-allowed-clients: []
  environment: "dev"
  host: "localhost"
  port: 8080
  protocol: "http"
