minio:
  endpoint: "localhost:9000"
  access-key-id: "your-access-key-id"
  secret-access-key: "your-secret-access-key"
  encryption-key-id: "your-encryption-key-id"
  bucket: "devbucket"
  region: "us-east-1"
  enable-multipart-upload: true
  file-chunk-size: 5 # Minimum 5MiB

# Server configurations
server:
  port: 8080
